# Generated by Django 4.1.4 on 2023-01-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_article_category_article_image_one_article_image_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_one',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_two',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
