# Generated by Django 4.1.4 on 2023-01-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_article_image_one_alter_article_image_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_one',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_two',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
